package cn.blooming.bep.crawler.model.entity;

public class Bank {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank.code
	 * @return  the value of bank.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank.code
	 * @param code  the value for bank.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank.name
	 * @return  the value of bank.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank.name
	 * @param name  the value for bank.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}
}