package cn.blooming.bep.crawler.model.entity;

public class Cardbin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cardbin.cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String cardbin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cardbin.bank_code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cardbin.bank_name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cardbin.card_type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String cardType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cardbin.status
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cardbin.cardbin
	 * @return  the value of cardbin.cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getCardbin() {
		return cardbin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cardbin.cardbin
	 * @param cardbin  the value for cardbin.cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setCardbin(String cardbin) {
		this.cardbin = cardbin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cardbin.bank_code
	 * @return  the value of cardbin.bank_code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cardbin.bank_code
	 * @param bankCode  the value for cardbin.bank_code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cardbin.bank_name
	 * @return  the value of cardbin.bank_name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cardbin.bank_name
	 * @param bankName  the value for cardbin.bank_name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cardbin.card_type
	 * @return  the value of cardbin.card_type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getCardType() {
		return cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cardbin.card_type
	 * @param cardType  the value for cardbin.card_type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cardbin.status
	 * @return  the value of cardbin.status
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cardbin.status
	 * @param status  the value for cardbin.status
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}