package cn.blooming.bep.crawler.model.entity;

import java.util.ArrayList;
import java.util.List;

public class CardbinExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public CardbinExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCardbinIsNull() {
			addCriterion("cardbin is null");
			return (Criteria) this;
		}

		public Criteria andCardbinIsNotNull() {
			addCriterion("cardbin is not null");
			return (Criteria) this;
		}

		public Criteria andCardbinEqualTo(String value) {
			addCriterion("cardbin =", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinNotEqualTo(String value) {
			addCriterion("cardbin <>", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinGreaterThan(String value) {
			addCriterion("cardbin >", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinGreaterThanOrEqualTo(String value) {
			addCriterion("cardbin >=", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinLessThan(String value) {
			addCriterion("cardbin <", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinLessThanOrEqualTo(String value) {
			addCriterion("cardbin <=", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinLike(String value) {
			addCriterion("cardbin like", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinNotLike(String value) {
			addCriterion("cardbin not like", value, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinIn(List<String> values) {
			addCriterion("cardbin in", values, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinNotIn(List<String> values) {
			addCriterion("cardbin not in", values, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinBetween(String value1, String value2) {
			addCriterion("cardbin between", value1, value2, "cardbin");
			return (Criteria) this;
		}

		public Criteria andCardbinNotBetween(String value1, String value2) {
			addCriterion("cardbin not between", value1, value2, "cardbin");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNull() {
			addCriterion("bank_code is null");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNotNull() {
			addCriterion("bank_code is not null");
			return (Criteria) this;
		}

		public Criteria andBankCodeEqualTo(String value) {
			addCriterion("bank_code =", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotEqualTo(String value) {
			addCriterion("bank_code <>", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThan(String value) {
			addCriterion("bank_code >", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
			addCriterion("bank_code >=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThan(String value) {
			addCriterion("bank_code <", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThanOrEqualTo(String value) {
			addCriterion("bank_code <=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLike(String value) {
			addCriterion("bank_code like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotLike(String value) {
			addCriterion("bank_code not like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeIn(List<String> values) {
			addCriterion("bank_code in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotIn(List<String> values) {
			addCriterion("bank_code not in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeBetween(String value1, String value2) {
			addCriterion("bank_code between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotBetween(String value1, String value2) {
			addCriterion("bank_code not between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNull() {
			addCriterion("bank_name is null");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNotNull() {
			addCriterion("bank_name is not null");
			return (Criteria) this;
		}

		public Criteria andBankNameEqualTo(String value) {
			addCriterion("bank_name =", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotEqualTo(String value) {
			addCriterion("bank_name <>", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThan(String value) {
			addCriterion("bank_name >", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("bank_name >=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThan(String value) {
			addCriterion("bank_name <", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThanOrEqualTo(String value) {
			addCriterion("bank_name <=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLike(String value) {
			addCriterion("bank_name like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotLike(String value) {
			addCriterion("bank_name not like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameIn(List<String> values) {
			addCriterion("bank_name in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotIn(List<String> values) {
			addCriterion("bank_name not in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameBetween(String value1, String value2) {
			addCriterion("bank_name between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotBetween(String value1, String value2) {
			addCriterion("bank_name not between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andCardTypeIsNull() {
			addCriterion("card_type is null");
			return (Criteria) this;
		}

		public Criteria andCardTypeIsNotNull() {
			addCriterion("card_type is not null");
			return (Criteria) this;
		}

		public Criteria andCardTypeEqualTo(String value) {
			addCriterion("card_type =", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeNotEqualTo(String value) {
			addCriterion("card_type <>", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeGreaterThan(String value) {
			addCriterion("card_type >", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
			addCriterion("card_type >=", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeLessThan(String value) {
			addCriterion("card_type <", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeLessThanOrEqualTo(String value) {
			addCriterion("card_type <=", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeLike(String value) {
			addCriterion("card_type like", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeNotLike(String value) {
			addCriterion("card_type not like", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeIn(List<String> values) {
			addCriterion("card_type in", values, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeNotIn(List<String> values) {
			addCriterion("card_type not in", values, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeBetween(String value1, String value2) {
			addCriterion("card_type between", value1, value2, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeNotBetween(String value1, String value2) {
			addCriterion("card_type not between", value1, value2, "cardType");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cardbin
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cardbin
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 28 13:48:20 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}