package cn.blooming.bep.crawler.model.entity;

public class FundHouse {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_house.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_house.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_house.code
	 * @return  the value of fund_house.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_house.code
	 * @param code  the value for fund_house.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_house.name
	 * @return  the value of fund_house.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_house.name
	 * @param name  the value for fund_house.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	public FundHouse() {
	}

	public FundHouse(String code, String name) {
		this.code = code;
		this.name = name;
	}

	@Override
	public String toString() {
		return "FundHouse{" +
				"code='" + code + '\'' +
				", name='" + name + '\'' +
				'}';
	}
}