package cn.blooming.bep.crawler.model.entity;

import java.util.Date;

public class FundStatisticsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.fund_type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String fundType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private Date date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.fund_type
	 * @return  the value of fund_statistics.fund_type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getFundType() {
		return fundType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.fund_type
	 * @param fundType  the value for fund_statistics.fund_type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.date
	 * @return  the value of fund_statistics.date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.date
	 * @param date  the value for fund_statistics.date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setDate(Date date) {
		this.date = date;
	}
}