package cn.blooming.bep.crawler.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FundStatistics extends FundStatisticsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.rate
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.updated
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private Date updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average_7days
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average7days;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average_1month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average1month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average_3month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average3month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average_6month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average6month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average_1year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average1year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average_2year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average2year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_statistics.average_3year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal average3year;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average
	 * @return  the value of fund_statistics.average
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage() {
		return average;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average
	 * @param average  the value for fund_statistics.average
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage(BigDecimal average) {
		this.average = average;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.rate
	 * @return  the value of fund_statistics.rate
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.rate
	 * @param rate  the value for fund_statistics.rate
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.updated
	 * @return  the value of fund_statistics.updated
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Date getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.updated
	 * @param updated  the value for fund_statistics.updated
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average_7days
	 * @return  the value of fund_statistics.average_7days
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage7days() {
		return average7days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average_7days
	 * @param average7days  the value for fund_statistics.average_7days
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage7days(BigDecimal average7days) {
		this.average7days = average7days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average_1month
	 * @return  the value of fund_statistics.average_1month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage1month() {
		return average1month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average_1month
	 * @param average1month  the value for fund_statistics.average_1month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage1month(BigDecimal average1month) {
		this.average1month = average1month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average_3month
	 * @return  the value of fund_statistics.average_3month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage3month() {
		return average3month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average_3month
	 * @param average3month  the value for fund_statistics.average_3month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage3month(BigDecimal average3month) {
		this.average3month = average3month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average_6month
	 * @return  the value of fund_statistics.average_6month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage6month() {
		return average6month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average_6month
	 * @param average6month  the value for fund_statistics.average_6month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage6month(BigDecimal average6month) {
		this.average6month = average6month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average_1year
	 * @return  the value of fund_statistics.average_1year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage1year() {
		return average1year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average_1year
	 * @param average1year  the value for fund_statistics.average_1year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage1year(BigDecimal average1year) {
		this.average1year = average1year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average_2year
	 * @return  the value of fund_statistics.average_2year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage2year() {
		return average2year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average_2year
	 * @param average2year  the value for fund_statistics.average_2year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage2year(BigDecimal average2year) {
		this.average2year = average2year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_statistics.average_3year
	 * @return  the value of fund_statistics.average_3year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getAverage3year() {
		return average3year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_statistics.average_3year
	 * @param average3year  the value for fund_statistics.average_3year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setAverage3year(BigDecimal average3year) {
		this.average3year = average3year;
	}

	@Override
	public String toString() {
		return "FundStatistics{" +
				"average=" + average +
				", rate=" + rate +
				", updated=" + updated +
				", average7days=" + average7days +
				", average1month=" + average1month +
				", average3month=" + average3month +
				", average6month=" + average6month +
				", average1year=" + average1year +
				", average2year=" + average2year +
				", average3year=" + average3year +
				'}';
	}
}