package cn.blooming.bep.crawler.model.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public FundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeIsNull() {
            addCriterion("fund_house_code is null");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeIsNotNull() {
            addCriterion("fund_house_code is not null");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeEqualTo(String value) {
            addCriterion("fund_house_code =", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeNotEqualTo(String value) {
            addCriterion("fund_house_code <>", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeGreaterThan(String value) {
            addCriterion("fund_house_code >", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_house_code >=", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeLessThan(String value) {
            addCriterion("fund_house_code <", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeLessThanOrEqualTo(String value) {
            addCriterion("fund_house_code <=", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeLike(String value) {
            addCriterion("fund_house_code like", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeNotLike(String value) {
            addCriterion("fund_house_code not like", value, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeIn(List<String> values) {
            addCriterion("fund_house_code in", values, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeNotIn(List<String> values) {
            addCriterion("fund_house_code not in", values, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeBetween(String value1, String value2) {
            addCriterion("fund_house_code between", value1, value2, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andFundHouseCodeNotBetween(String value1, String value2) {
            addCriterion("fund_house_code not between", value1, value2, "fundHouseCode");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearIsNull() {
            addCriterion("rate_current_year is null");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearIsNotNull() {
            addCriterion("rate_current_year is not null");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearEqualTo(BigDecimal value) {
            addCriterion("rate_current_year =", value, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearNotEqualTo(BigDecimal value) {
            addCriterion("rate_current_year <>", value, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearGreaterThan(BigDecimal value) {
            addCriterion("rate_current_year >", value, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_current_year >=", value, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearLessThan(BigDecimal value) {
            addCriterion("rate_current_year <", value, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_current_year <=", value, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearIn(List<BigDecimal> values) {
            addCriterion("rate_current_year in", values, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearNotIn(List<BigDecimal> values) {
            addCriterion("rate_current_year not in", values, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_current_year between", value1, value2, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRateCurrentYearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_current_year not between", value1, value2, "rateCurrentYear");
            return (Criteria) this;
        }

        public Criteria andRate7daysIsNull() {
            addCriterion("rate_7days is null");
            return (Criteria) this;
        }

        public Criteria andRate7daysIsNotNull() {
            addCriterion("rate_7days is not null");
            return (Criteria) this;
        }

        public Criteria andRate7daysEqualTo(BigDecimal value) {
            addCriterion("rate_7days =", value, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysNotEqualTo(BigDecimal value) {
            addCriterion("rate_7days <>", value, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysGreaterThan(BigDecimal value) {
            addCriterion("rate_7days >", value, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_7days >=", value, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysLessThan(BigDecimal value) {
            addCriterion("rate_7days <", value, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_7days <=", value, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysIn(List<BigDecimal> values) {
            addCriterion("rate_7days in", values, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysNotIn(List<BigDecimal> values) {
            addCriterion("rate_7days not in", values, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_7days between", value1, value2, "rate7days");
            return (Criteria) this;
        }

        public Criteria andRate7daysNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_7days not between", value1, value2, "rate7days");
            return (Criteria) this;
        }

        public Criteria andNetValueIsNull() {
            addCriterion("net_value is null");
            return (Criteria) this;
        }

        public Criteria andNetValueIsNotNull() {
            addCriterion("net_value is not null");
            return (Criteria) this;
        }

        public Criteria andNetValueEqualTo(BigDecimal value) {
            addCriterion("net_value =", value, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueNotEqualTo(BigDecimal value) {
            addCriterion("net_value <>", value, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueGreaterThan(BigDecimal value) {
            addCriterion("net_value >", value, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("net_value >=", value, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueLessThan(BigDecimal value) {
            addCriterion("net_value <", value, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("net_value <=", value, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueIn(List<BigDecimal> values) {
            addCriterion("net_value in", values, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueNotIn(List<BigDecimal> values) {
            addCriterion("net_value not in", values, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_value between", value1, value2, "netValue");
            return (Criteria) this;
        }

        public Criteria andNetValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_value not between", value1, value2, "netValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueIsNull() {
            addCriterion("rate_net_value is null");
            return (Criteria) this;
        }

        public Criteria andRateNetValueIsNotNull() {
            addCriterion("rate_net_value is not null");
            return (Criteria) this;
        }

        public Criteria andRateNetValueEqualTo(BigDecimal value) {
            addCriterion("rate_net_value =", value, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueNotEqualTo(BigDecimal value) {
            addCriterion("rate_net_value <>", value, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueGreaterThan(BigDecimal value) {
            addCriterion("rate_net_value >", value, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_net_value >=", value, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueLessThan(BigDecimal value) {
            addCriterion("rate_net_value <", value, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_net_value <=", value, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueIn(List<BigDecimal> values) {
            addCriterion("rate_net_value in", values, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueNotIn(List<BigDecimal> values) {
            addCriterion("rate_net_value not in", values, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_net_value between", value1, value2, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andRateNetValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_net_value not between", value1, value2, "rateNetValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueIsNull() {
            addCriterion("total_value is null");
            return (Criteria) this;
        }

        public Criteria andTotalValueIsNotNull() {
            addCriterion("total_value is not null");
            return (Criteria) this;
        }

        public Criteria andTotalValueEqualTo(BigDecimal value) {
            addCriterion("total_value =", value, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueNotEqualTo(BigDecimal value) {
            addCriterion("total_value <>", value, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueGreaterThan(BigDecimal value) {
            addCriterion("total_value >", value, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_value >=", value, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueLessThan(BigDecimal value) {
            addCriterion("total_value <", value, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_value <=", value, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueIn(List<BigDecimal> values) {
            addCriterion("total_value in", values, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueNotIn(List<BigDecimal> values) {
            addCriterion("total_value not in", values, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_value between", value1, value2, "totalValue");
            return (Criteria) this;
        }

        public Criteria andTotalValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_value not between", value1, value2, "totalValue");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterionForJDBCDate("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterionForJDBCDate("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterionForJDBCDate("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andRateMonthIsNull() {
            addCriterion("rate_month is null");
            return (Criteria) this;
        }

        public Criteria andRateMonthIsNotNull() {
            addCriterion("rate_month is not null");
            return (Criteria) this;
        }

        public Criteria andRateMonthEqualTo(BigDecimal value) {
            addCriterion("rate_month =", value, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthNotEqualTo(BigDecimal value) {
            addCriterion("rate_month <>", value, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthGreaterThan(BigDecimal value) {
            addCriterion("rate_month >", value, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_month >=", value, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthLessThan(BigDecimal value) {
            addCriterion("rate_month <", value, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_month <=", value, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthIn(List<BigDecimal> values) {
            addCriterion("rate_month in", values, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthNotIn(List<BigDecimal> values) {
            addCriterion("rate_month not in", values, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_month between", value1, value2, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateMonthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_month not between", value1, value2, "rateMonth");
            return (Criteria) this;
        }

        public Criteria andRateQuarterIsNull() {
            addCriterion("rate_quarter is null");
            return (Criteria) this;
        }

        public Criteria andRateQuarterIsNotNull() {
            addCriterion("rate_quarter is not null");
            return (Criteria) this;
        }

        public Criteria andRateQuarterEqualTo(BigDecimal value) {
            addCriterion("rate_quarter =", value, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterNotEqualTo(BigDecimal value) {
            addCriterion("rate_quarter <>", value, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterGreaterThan(BigDecimal value) {
            addCriterion("rate_quarter >", value, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_quarter >=", value, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterLessThan(BigDecimal value) {
            addCriterion("rate_quarter <", value, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_quarter <=", value, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterIn(List<BigDecimal> values) {
            addCriterion("rate_quarter in", values, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterNotIn(List<BigDecimal> values) {
            addCriterion("rate_quarter not in", values, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_quarter between", value1, value2, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateQuarterNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_quarter not between", value1, value2, "rateQuarter");
            return (Criteria) this;
        }

        public Criteria andRateHalfIsNull() {
            addCriterion("rate_half is null");
            return (Criteria) this;
        }

        public Criteria andRateHalfIsNotNull() {
            addCriterion("rate_half is not null");
            return (Criteria) this;
        }

        public Criteria andRateHalfEqualTo(BigDecimal value) {
            addCriterion("rate_half =", value, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfNotEqualTo(BigDecimal value) {
            addCriterion("rate_half <>", value, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfGreaterThan(BigDecimal value) {
            addCriterion("rate_half >", value, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_half >=", value, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfLessThan(BigDecimal value) {
            addCriterion("rate_half <", value, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_half <=", value, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfIn(List<BigDecimal> values) {
            addCriterion("rate_half in", values, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfNotIn(List<BigDecimal> values) {
            addCriterion("rate_half not in", values, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_half between", value1, value2, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateHalfNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_half not between", value1, value2, "rateHalf");
            return (Criteria) this;
        }

        public Criteria andRateYearIsNull() {
            addCriterion("rate_year is null");
            return (Criteria) this;
        }

        public Criteria andRateYearIsNotNull() {
            addCriterion("rate_year is not null");
            return (Criteria) this;
        }

        public Criteria andRateYearEqualTo(BigDecimal value) {
            addCriterion("rate_year =", value, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearNotEqualTo(BigDecimal value) {
            addCriterion("rate_year <>", value, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearGreaterThan(BigDecimal value) {
            addCriterion("rate_year >", value, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_year >=", value, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearLessThan(BigDecimal value) {
            addCriterion("rate_year <", value, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_year <=", value, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearIn(List<BigDecimal> values) {
            addCriterion("rate_year in", values, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearNotIn(List<BigDecimal> values) {
            addCriterion("rate_year not in", values, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_year between", value1, value2, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateYearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_year not between", value1, value2, "rateYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearIsNull() {
            addCriterion("rate_three_year is null");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearIsNotNull() {
            addCriterion("rate_three_year is not null");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearEqualTo(BigDecimal value) {
            addCriterion("rate_three_year =", value, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearNotEqualTo(BigDecimal value) {
            addCriterion("rate_three_year <>", value, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearGreaterThan(BigDecimal value) {
            addCriterion("rate_three_year >", value, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_three_year >=", value, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearLessThan(BigDecimal value) {
            addCriterion("rate_three_year <", value, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_three_year <=", value, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearIn(List<BigDecimal> values) {
            addCriterion("rate_three_year in", values, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearNotIn(List<BigDecimal> values) {
            addCriterion("rate_three_year not in", values, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_three_year between", value1, value2, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateThreeYearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_three_year not between", value1, value2, "rateThreeYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearIsNull() {
            addCriterion("rate_five_year is null");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearIsNotNull() {
            addCriterion("rate_five_year is not null");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearEqualTo(BigDecimal value) {
            addCriterion("rate_five_year =", value, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearNotEqualTo(BigDecimal value) {
            addCriterion("rate_five_year <>", value, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearGreaterThan(BigDecimal value) {
            addCriterion("rate_five_year >", value, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_five_year >=", value, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearLessThan(BigDecimal value) {
            addCriterion("rate_five_year <", value, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_five_year <=", value, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearIn(List<BigDecimal> values) {
            addCriterion("rate_five_year in", values, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearNotIn(List<BigDecimal> values) {
            addCriterion("rate_five_year not in", values, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_five_year between", value1, value2, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateFiveYearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_five_year not between", value1, value2, "rateFiveYear");
            return (Criteria) this;
        }

        public Criteria andRateStartIsNull() {
            addCriterion("rate_start is null");
            return (Criteria) this;
        }

        public Criteria andRateStartIsNotNull() {
            addCriterion("rate_start is not null");
            return (Criteria) this;
        }

        public Criteria andRateStartEqualTo(BigDecimal value) {
            addCriterion("rate_start =", value, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartNotEqualTo(BigDecimal value) {
            addCriterion("rate_start <>", value, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartGreaterThan(BigDecimal value) {
            addCriterion("rate_start >", value, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_start >=", value, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartLessThan(BigDecimal value) {
            addCriterion("rate_start <", value, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_start <=", value, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartIn(List<BigDecimal> values) {
            addCriterion("rate_start in", values, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartNotIn(List<BigDecimal> values) {
            addCriterion("rate_start not in", values, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_start between", value1, value2, "rateStart");
            return (Criteria) this;
        }

        public Criteria andRateStartNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_start not between", value1, value2, "rateStart");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterionForJDBCDate("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIsNull() {
            addCriterion("risk_level is null");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIsNotNull() {
            addCriterion("risk_level is not null");
            return (Criteria) this;
        }

        public Criteria andRiskLevelEqualTo(String value) {
            addCriterion("risk_level =", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotEqualTo(String value) {
            addCriterion("risk_level <>", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelGreaterThan(String value) {
            addCriterion("risk_level >", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelGreaterThanOrEqualTo(String value) {
            addCriterion("risk_level >=", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelLessThan(String value) {
            addCriterion("risk_level <", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelLessThanOrEqualTo(String value) {
            addCriterion("risk_level <=", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelLike(String value) {
            addCriterion("risk_level like", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotLike(String value) {
            addCriterion("risk_level not like", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIn(List<String> values) {
            addCriterion("risk_level in", values, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotIn(List<String> values) {
            addCriterion("risk_level not in", values, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelBetween(String value1, String value2) {
            addCriterion("risk_level between", value1, value2, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotBetween(String value1, String value2) {
            addCriterion("risk_level not between", value1, value2, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andScaleIsNull() {
            addCriterion("scale is null");
            return (Criteria) this;
        }

        public Criteria andScaleIsNotNull() {
            addCriterion("scale is not null");
            return (Criteria) this;
        }

        public Criteria andScaleEqualTo(BigDecimal value) {
            addCriterion("scale =", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleNotEqualTo(BigDecimal value) {
            addCriterion("scale <>", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleGreaterThan(BigDecimal value) {
            addCriterion("scale >", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("scale >=", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleLessThan(BigDecimal value) {
            addCriterion("scale <", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleLessThanOrEqualTo(BigDecimal value) {
            addCriterion("scale <=", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleIn(List<BigDecimal> values) {
            addCriterion("scale in", values, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleNotIn(List<BigDecimal> values) {
            addCriterion("scale not in", values, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("scale between", value1, value2, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("scale not between", value1, value2, "scale");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 10 14:50:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund
     *
     * @mbg.generated Thu Jan 10 14:50:37 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}