package cn.blooming.bep.crawler.model.entity;

import org.apache.commons.lang3.time.DateFormatUtils;

import java.math.BigDecimal;

public class FundHistory extends FundHistoryKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_history.net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal netValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_history.total_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal totalValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_history.rate_net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateNetValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_history.net_value
	 * @return  the value of fund_history.net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getNetValue() {
		return netValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_history.net_value
	 * @param netValue  the value for fund_history.net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setNetValue(BigDecimal netValue) {
		this.netValue = netValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_history.total_value
	 * @return  the value of fund_history.total_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getTotalValue() {
		return totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_history.total_value
	 * @param totalValue  the value for fund_history.total_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setTotalValue(BigDecimal totalValue) {
		this.totalValue = totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_history.rate_net_value
	 * @return  the value of fund_history.rate_net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateNetValue() {
		return rateNetValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_history.rate_net_value
	 * @param rateNetValue  the value for fund_history.rate_net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateNetValue(BigDecimal rateNetValue) {
		this.rateNetValue = rateNetValue;
	}

	@Override
	public String toString() {
        String format = DateFormatUtils.format(super.getDate(), "yyyy-MM-dd");
        return "FundHistory{" +
				"netValue=" + netValue +
				", date=" + format +
				", code=" + super.getCode() +
				", totalValue=" + totalValue +
				", rateNetValue=" + rateNetValue +
				'}';
	}
}