package cn.blooming.bep.crawler.model.entity;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class FundHistoryKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_history.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund_history.date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private Date date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_history.code
	 * @return  the value of fund_history.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_history.code
	 * @param code  the value for fund_history.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund_history.date
	 * @return  the value of fund_history.date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund_history.date
	 * @param date  the value for fund_history.date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setDate(Date date) {
		this.date = date;
	}
}