package cn.blooming.bep.crawler.model.entity;

import java.math.BigDecimal;
import java.util.Date;
/**
 * 		code 		基金代码 1
 * 		name 		基金名称 1
 * 		type 		基金类别 stock: 股票�? mix：混合型 bond: 债券�? index: 指数�? etf: ETF连接�? QDII: QDII LOF: LOF FOF: FOF 1
 *                           sf:分级�?/结构�? gf:保本�?
 * 		fund_house_code 基金公司代码 1
 * 		net_value 		单位�?�? 1
 * 		rate_net_value 	征税估定价�?? 1
 * 		total_value 	累计�?�? 1
 * 		updated_time 	更新日期 1
 * 		rate_month 	上一月收益率 1
 * 		rate_quarter 	上一季度收益�? 1
 * 		rate_half 	半年收益�? 1
 * 		rate_year 	上一年度收益�? 1
 * 		rate_three_year 三年收益�? 1
 * 		rate_five_year 	五年收益�? null
 * 		rate_start 	自成立日起的收益�? 1
 * 		start_date 	成立�?			 1
 * 		risk_level 	风险等级 R1 谨慎�? R2 稳健�? R3 平衡�? R4 进取�? R5 �?进型 1
 * 		scale 		基金规模 (单位�?) 1
 * 		level 		基金评级 1
 * */
public class Fund {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.fund_house_code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String fundHouseCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_current_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateCurrentYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_7days
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rate7days;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal netValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateNetValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.total_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal totalValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.updated_time
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private Date updatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateMonth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_quarter
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateQuarter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_half
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateHalf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_three_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateThreeYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_five_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateFiveYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.rate_start
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal rateStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.start_date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.risk_level
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String riskLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.scale
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private BigDecimal scale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fund.level
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	private String level;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.code
	 * @return  the value of fund.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.code
	 * @param code  the value for fund.code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.name
	 * @return  the value of fund.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.name
	 * @param name  the value for fund.name
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.type
	 * @return  the value of fund.type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.type
	 * @param type  the value for fund.type
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.fund_house_code
	 * @return  the value of fund.fund_house_code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getFundHouseCode() {
		return fundHouseCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.fund_house_code
	 * @param fundHouseCode  the value for fund.fund_house_code
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setFundHouseCode(String fundHouseCode) {
		this.fundHouseCode = fundHouseCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_current_year
	 * @return  the value of fund.rate_current_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateCurrentYear() {
		return rateCurrentYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_current_year
	 * @param rateCurrentYear  the value for fund.rate_current_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateCurrentYear(BigDecimal rateCurrentYear) {
		this.rateCurrentYear = rateCurrentYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_7days
	 * @return  the value of fund.rate_7days
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRate7days() {
		return rate7days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_7days
	 * @param rate7days  the value for fund.rate_7days
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRate7days(BigDecimal rate7days) {
		this.rate7days = rate7days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.net_value
	 * @return  the value of fund.net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getNetValue() {
		return netValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.net_value
	 * @param netValue  the value for fund.net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setNetValue(BigDecimal netValue) {
		this.netValue = netValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_net_value
	 * @return  the value of fund.rate_net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateNetValue() {
		return rateNetValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_net_value
	 * @param rateNetValue  the value for fund.rate_net_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateNetValue(BigDecimal rateNetValue) {
		this.rateNetValue = rateNetValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.total_value
	 * @return  the value of fund.total_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getTotalValue() {
		return totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.total_value
	 * @param totalValue  the value for fund.total_value
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setTotalValue(BigDecimal totalValue) {
		this.totalValue = totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.updated_time
	 * @return  the value of fund.updated_time
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.updated_time
	 * @param updatedTime  the value for fund.updated_time
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_month
	 * @return  the value of fund.rate_month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateMonth() {
		return rateMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_month
	 * @param rateMonth  the value for fund.rate_month
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateMonth(BigDecimal rateMonth) {
		this.rateMonth = rateMonth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_quarter
	 * @return  the value of fund.rate_quarter
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateQuarter() {
		return rateQuarter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_quarter
	 * @param rateQuarter  the value for fund.rate_quarter
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateQuarter(BigDecimal rateQuarter) {
		this.rateQuarter = rateQuarter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_half
	 * @return  the value of fund.rate_half
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateHalf() {
		return rateHalf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_half
	 * @param rateHalf  the value for fund.rate_half
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateHalf(BigDecimal rateHalf) {
		this.rateHalf = rateHalf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_year
	 * @return  the value of fund.rate_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateYear() {
		return rateYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_year
	 * @param rateYear  the value for fund.rate_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateYear(BigDecimal rateYear) {
		this.rateYear = rateYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_three_year
	 * @return  the value of fund.rate_three_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateThreeYear() {
		return rateThreeYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_three_year
	 * @param rateThreeYear  the value for fund.rate_three_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateThreeYear(BigDecimal rateThreeYear) {
		this.rateThreeYear = rateThreeYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_five_year
	 * @return  the value of fund.rate_five_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateFiveYear() {
		return rateFiveYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_five_year
	 * @param rateFiveYear  the value for fund.rate_five_year
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateFiveYear(BigDecimal rateFiveYear) {
		this.rateFiveYear = rateFiveYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.rate_start
	 * @return  the value of fund.rate_start
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getRateStart() {
		return rateStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.rate_start
	 * @param rateStart  the value for fund.rate_start
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRateStart(BigDecimal rateStart) {
		this.rateStart = rateStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.start_date
	 * @return  the value of fund.start_date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.start_date
	 * @param startDate  the value for fund.start_date
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.risk_level
	 * @return  the value of fund.risk_level
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getRiskLevel() {
		return riskLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.risk_level
	 * @param riskLevel  the value for fund.risk_level
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setRiskLevel(String riskLevel) {
		this.riskLevel = riskLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.scale
	 * @return  the value of fund.scale
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public BigDecimal getScale() {
		return scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.scale
	 * @param scale  the value for fund.scale
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setScale(BigDecimal scale) {
		this.scale = scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fund.level
	 * @return  the value of fund.level
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fund.level
	 * @param level  the value for fund.level
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	@Override
	public String toString() {
		return "Fund{" +
				"code='" + code + '\'' +
				", name='" + name + '\'' +
				", type='" + type + '\'' +
				", fundHouseCode='" + fundHouseCode + '\'' +
				", rateCurrentYear=" + rateCurrentYear +
				", rate7days=" + rate7days +
				", netValue=" + netValue +
				", rateNetValue=" + rateNetValue +
				", totalValue=" + totalValue +
				", updatedTime=" + updatedTime +
				", rateMonth=" + rateMonth +
				", rateQuarter=" + rateQuarter +
				", rateHalf=" + rateHalf +
				", rateYear=" + rateYear +
				", rateThreeYear=" + rateThreeYear +
				", rateFiveYear=" + rateFiveYear +
				", rateStart=" + rateStart +
				", startDate=" + startDate +
				", riskLevel='" + riskLevel + '\'' +
				", scale=" + scale +
				", level='" + level + '\'' +
				'}';
	}
}