package cn.blooming.bep.crawler.model.mapper;

import cn.blooming.bep.crawler.model.entity.FundHouse;
import cn.blooming.bep.crawler.model.entity.FundHouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundHouseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	long countByExample(FundHouseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int deleteByExample(FundHouseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int insert(FundHouse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int insertSelective(FundHouse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	List<FundHouse> selectByExample(FundHouseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	FundHouse selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByExampleSelective(@Param("record") FundHouse record, @Param("example") FundHouseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByExample(@Param("record") FundHouse record, @Param("example") FundHouseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByPrimaryKeySelective(FundHouse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund_house
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByPrimaryKey(FundHouse record);
}