package cn.blooming.bep.crawler.model.mapper;

import cn.blooming.bep.crawler.model.entity.Fund;
import cn.blooming.bep.crawler.model.entity.FundExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	long countByExample(FundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int deleteByExample(FundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int insert(Fund record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int insertSelective(Fund record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	List<Fund> selectByExample(FundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	Fund selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Fund record, @Param("example") FundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByExample(@Param("record") Fund record, @Param("example") FundExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByPrimaryKeySelective(Fund record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fund
	 * @mbg.generated  Thu Jan 10 14:50:37 CST 2019
	 */
	int updateByPrimaryKey(Fund record);
}